### 查询课程信息
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODg4OTQyOTMsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImEyM2ZkMWQ3LTY1M2YtNDRkYi1hOWZmLTFkYzU3MmFlNTJkNSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.M9-tCNvu_Ui_32yaE9OVkWSZ2o8O-Xb5Pm4JiVSaSok

{
  "auditStatus": "202003",
  "courseName": "java",
  "publishStatus": ""
}

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

### 新增课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 10,
  "originalPrice": 100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "test",
  "pic": "test_pic",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "test_tags",
  "grade": "204001",
  "description": "test_测试课程,test_测试课程,test_测试课程"
}

### 新增课程异常测试
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 10,
  "originalPrice": 100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "test_pic",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "test_tags",
  "grade": "204001",
  "description": "test_测试课程,test_测试课程,test_测试课程"
}

### 课程查询
GET {{content_host}}/content/course/133
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODg4OTQyOTMsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImEyM2ZkMWQ3LTY1M2YtNDRkYi1hOWZmLTFkYzU3MmFlNTJkNSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.M9-tCNvu_Ui_32yaE9OVkWSZ2o8O-Xb5Pm4JiVSaSok


### 修改课程
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 40,
  "name": "SpringBoot核心hhh",
  "users": "Spring Boot初学者",
  "tags": "Spring项目的快速构建",
  "mt": "1-3",
  "st": "1-3-2",
  "grade": "200003",
  "teachmode": "201001",
  "description": "课程系统性地深度探讨 Spring Boot 核心特性，引导小伙伴对 Java 规范的重视，启发对技术原理性的思考，掌握排查问题的技能，以及学习阅读源码的方法和技巧，全面提升研发能力，进军架构师队伍。",
  "pic": "https://cdn.educba.com/academy/wp-content/uploads/2018/08/Spring-BOOT-Interview-questions.jpg",
  "charge": "201001",
  "price": 100
}

### 删除课程
DELETE {{content_host}}/content/course/133
Content-Type: application/json

### 查询课程计划
GET {{content_host}}/content/teachplan/117/tree-nodes
Content-Type: application/json

### 删除课程计划
DELETE {{content_host}}/content/teachplan/297
Content-Type: application/json

### 移动课程计划位置(moveup/movedown)
POST {{content_host}}/content/teachplan/moveup/276
Content-Type: application/json

### 查询课程对应老师信息
GET {{content_host}}/content/courseTeacher/list/133
Content-Type: application/json

### 添加课程对应老师信息
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": null,
  "courseId": 75,
  "teacherName": "王老师哈哈",
  "position": "教师职位",
  "introduction": "教师简介",
  "photograph": null,
  "createDate": null
}

### 修改课程对应老师信息
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 37,
  "courseId": 75,
  "teacherName": "王老师ppp",
  "position": "教师职位",
  "introduction": "教师简介",
  "photograph": null,
  "createDate": "2023-07-02 15:13:44"
}

### 删除课程对应老师信息 (/ourseTeacher/course/课程id/教师id)
DELETE {{content_host}}/content/courseTeacher/course/75/22
Content-Type: application/json

### 网关访问课程查询
GET {{gateway_host}}/content/course/117
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQxXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4ODk2MzE0MywiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiJjOWNhNzIyYy1hNzU3LTQ1NTgtYWI2MS1hMGQ0NzMyMzhiNTciLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.6u7Tg15gi6yVplaNpfB9MYFOF6ht6B65XjnJ31iaFm0

